/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CourseCard: typeof import('./src/components/CourseCard.vue')['default']
    CourseList: typeof import('./src/components/CourseList.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelperCollapse: typeof import('./src/components/HelperCollapse.vue')['default']
    KingArea: typeof import('./src/components/KingArea.vue')['default']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
